baseURL = "https://my-hugo-site-peach.vercel.app/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "custom-theme"

[params]
  rssStylesheet = "/rss-stylesheet.xsl"

[outputs]
  home = ["HTML", "RSS"]
  rss = ["RSS"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Questions"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
