baseURL = "https://<your-vercel-domain>"
languageCode = "en-us"
title = "My Hugo Site"
theme = "custom-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Questions"
    url = "/posts/"
    weight = 2
