baseURL = "https://my-hugo-site-a1e.pages.dev/"
languageCode = "en-us"
title = "My Hugo Site"
description = "A site for asking and answering questions, sharing updates, and more."
theme = "custom-theme"

[params]
  rssStylesheet = "/rss-stylesheet.xsl"

[outputs]
  home = ["HTML", "RSS"]
  rss = ["RSS"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Questions"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

  [[menu.main]]
    name = "Ask a Question"
    url = "/ask-question/"
    weight = 6

[params]
  author = "Your Name"
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

[taxonomies]
  category = "categories"
  tag = "tags"
